package normal.question_0389.FindTheDifference;

import org.junit.Test;

import java.util.Arrays;

/**
 * You are given two strings s and t.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * <p>
 * Return the letter that was added to t.
 * <p>
 * 给定两个字符串 s 和 t，它们只包含小写字母。
 * <p>
 * 字符串 t 由字符串 s 随机重排，然后在随机位置添加一个字母。
 * <p>
 * 请找出在 t 中被添加的字母。
 * 来源：力扣（LeetCode）
 * 链接：https://leetcode-cn.com/problems/find-the-difference
 * 著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。
 *
 * @author Jungle
 * @since 2021/9/29 23:49
 */
public class Solution {
    @Test
    public void test() {
        System.out.println(findTheDifference("abcd", "abcde"));
    }
    public char findTheDifferenceAgain(String s, String t) {
        char ret = 0;
        for (int i = 0; i < s.length(); i++) {
            ret ^= s.charAt(i);
        }
        for (int i = 0; i < t.length(); i++) {
            ret ^= t.charAt(i);
        }
        return ret;
    }
    public char findTheDifference(String s, String t) {
        char[] chars = (s + t).toCharArray();
        char ret = 0;
        for (char aChar : chars) {
            ret ^= aChar;
        }
        return ret;
    }


    public char findTheDifferenceOrigin(String s, String t) {
        char[] chars = s.toCharArray();
        char[] chart = t.toCharArray();
        Arrays.sort(chars);
        Arrays.sort(chart);
        for (int i = 0; i < chars.length; i++) {
            if (chars[i] != chart[i]) {
                return chart[i];
            }
        }
        return chart[chars.length];
    }
}
